# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfafe80f0fe632122beb375255606143347aa724f598432722289453ec91f731e7078d453b4578f7efc9c7976dd13b6f30babf15bf1ae4907d65d949a22c5a71

test:
  secret_key_base: 3de722dafc90b0cd1e7366df6ccce18844224b57426f59a87a9355b7590c0f4d6eb6364e7d2369a7f30ebf535a30bee016c7bb1ecc0c1e36a8161826efac51de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
